name: Update Release with ZIP

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  update-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          git archive --format zip --output ./repo.zip HEAD

      - name: Get the release ID for the "latest" tag
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const release = response.data.find(release => release.tag_name === 'latest');
            if (!release) {
              throw new Error('Release with tag "latest" not found');
            }
            core.setOutput('upload_url', release.upload_url);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload the ZIP to the release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./repo.zip
          asset_name: pack.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
